/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/trial.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/trial.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.51, 3.414, -3.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.773, 1, 1]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[5.78, 5.571, -4.069]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object006.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[5.78, 5.571, -4.069]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle481_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle481_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[-5.538, 3.354, 0.145]} rotation={[-Math.PI / 2, 0, -0.261]} scale={0.653}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[-5.525, 8.357, 0.052]} rotation={[0, -0.261, 0]} scale={0.76}>
        <mesh geometry={nodes.Box001.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[-7.284, 5.571, -22.899]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object007.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[-7.284, 5.571, -22.899]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle482_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle482_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[5.78, 5.571, -42.358]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object008.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[5.78, 5.571, -42.358]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle483_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle483_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[-7.284, 5.571, -58.905]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object009.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[-7.284, 5.571, -58.905]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle484_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle484_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[5.78, 5.571, -78.365]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object010.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[5.78, 5.571, -78.365]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle485_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle485_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[-7.284, 5.571, -99.13]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object011.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[-7.284, 5.571, -99.13]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle486_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle486_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[5.78, 5.571, -118.589]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object012.geometry} material={materials.Material__364} scale={0.025} />
      </group>
      <group position={[5.78, 5.571, -118.589]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group scale={0.025}>
          <mesh geometry={nodes.Rectangle487_1.geometry} material={materials['fallback Material']} />
          <mesh geometry={nodes.Rectangle487_2.geometry} material={materials['fallback Material']} />
        </group>
      </group>
      <group position={[-5.525, 8.357, -40.595]} rotation={[0, -0.261, 0]} scale={0.76}>
        <mesh geometry={nodes.Box002.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[-5.538, 3.354, -40.502]} rotation={[-Math.PI / 2, 0, -0.261]} scale={0.653}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[-5.525, 8.357, -78.927]} rotation={[0, -0.261, 0]} scale={0.76}>
        <mesh geometry={nodes.Box003.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[-5.538, 3.354, -78.833]} rotation={[-Math.PI / 2, 0, -0.261]} scale={0.653}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[-5.525, 8.357, -117.258]} rotation={[0, -0.261, 0]} scale={0.76}>
        <mesh geometry={nodes.Box004.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[-5.538, 3.354, -117.165]} rotation={[-Math.PI / 2, 0, -0.261]} scale={0.653}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[3.334, 8.357, -22.586]} rotation={[0, 0.525, 0]} scale={0.76}>
        <mesh geometry={nodes.Box005.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[3.391, 3.354, -22.511]} rotation={[-Math.PI / 2, 0, 0.525]} scale={0.653}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[3.334, 8.357, -60.484]} rotation={[0, 0.525, 0]} scale={0.76}>
        <mesh geometry={nodes.Box006.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[3.391, 3.354, -60.409]} rotation={[-Math.PI / 2, 0, 0.525]} scale={0.653}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[3.334, 8.357, -98.383]} rotation={[0, 0.525, 0]} scale={0.76}>
        <mesh geometry={nodes.Box007.geometry} material={materials.Material__437} scale={0.025} />
      </group>
      <group position={[3.391, 3.354, -98.308]} rotation={[-Math.PI / 2, 0, 0.525]} scale={0.653}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/trial.glb')
